### ISSUE TITLE
returns undefined

### ISSUE THREAD

**Issue by fortitude81** [fortitude81/HotOrCold#3]
this code returns "undefined" after entering a number into the prompt.  Cant figure out exactly why.

**Comment by trystant** [comment]
Let's go over this in session today so we can figure out how best to debug as well as to show this error.

**Comment by trystant** [comment]
While in session today, we showed how the code from the guessinggame can be paused and debugged in Chrome Developer tools. We also came to the realization that lines 9 and 10 of the `if` statement in guessing game will always return true. We discovered that after adding a `while` statement that matched the lifecycle of the assignment.

**Comment by fortitude81** [comment]
no longer returning "undefined"

**Comment by fortitude81** [comment]
made some changes to the code but still not working right. alert prompts are not working.

**Comment by fortitude81** [comment]
working good now, only one problem, the game keeps going after the game should be over.

**Comment by trystant** [comment]
The solution to this was to add a return value of `true` following the guess of the correct answer on line 22. The function guessingGame() was returning `false` in the absence of a value returned, and the `while (!correct) {` loop would repeat over and over.
